CREATE TABLE IF NOT EXISTS "cms_articles" (
  "id" serial PRIMARY KEY NOT NULL,
  "slug" varchar(255) NOT NULL,
  "title" text NOT NULL,
  "hook" text NOT NULL,
  "excerpt" text NOT NULL,
  "cms_template" varchar(50) NOT NULL,
  "display_template" varchar(50) NOT NULL,
  "category" varchar(50) NOT NULL,
  "topic" varchar(120) NOT NULL,
  "read_time" integer DEFAULT 5 NOT NULL,
  "published_at" timestamp NOT NULL,
  "author_name" varchar(120) NOT NULL,
  "author_role" varchar(120) NOT NULL,
  "featured" boolean DEFAULT false NOT NULL,
  "tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "cover_accent" varchar(120) DEFAULT 'from-brand-orange/15 via-brand-orange/5 to-transparent' NOT NULL,
  "hero_image_url" text,
  "attachment_url" text,
  "attachment_name" text,
  "content" jsonb NOT NULL,
  "status" varchar(20) DEFAULT 'draft' NOT NULL,
  "created_at" timestamp DEFAULT now(),
  "updated_at" timestamp DEFAULT now(),
  CONSTRAINT "cms_articles_slug_unique" UNIQUE("slug")
);
